# Generated by Django 3.2.5 on 2021-07-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('meter', models.CharField(max_length=50)),
                ('epa_energy_type', models.CharField(max_length=50)),
                ('allocated_consumption', models.FloatField()),
                ('consumption_unit', models.FloatField()),
                ('reading_type', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sqft', models.IntegerField(null=True)),
                ('agency', models.CharField(max_length=50)),
                ('building_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['agency'], name='facilities__agency_df21b9_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['building_type'], name='facilities__buildin_4cfae0_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['agency', 'building_type'], name='facilities__agency_ae60bc_idx'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddIndex(
            model_name='consumption',
            index=models.Index(fields=['facility'], name='facilities__facilit_5cd993_idx'),
        ),
        migrations.AddIndex(
            model_name='consumption',
            index=models.Index(fields=['facility', 'meter'], name='facilities__facilit_55456f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumption',
            index=models.Index(fields=['facility', 'year'], name='facilities__facilit_d00e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='consumption',
            index=models.Index(fields=['facility', 'month'], name='facilities__facilit_bcbd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='consumption',
            index=models.Index(fields=['facility', 'epa_energy_type'], name='facilities__facilit_f0262e_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumption',
            constraint=models.UniqueConstraint(fields=('account', 'meter', 'year', 'month'), name='consumption__constraint'),
        ),
    ]
