# Generated by Django 3.2.5 on 2021-07-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='consumption_unit',
            field=models.CharField(max_length=5),
        ),
    ]
