# Generated by Django 3.2.5 on 2021-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_fix_consumption_unit_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumption',
            name='consumption__constraint',
        ),
        migrations.AddConstraint(
            model_name='consumption',
            constraint=models.UniqueConstraint(fields=('facility', 'account', 'meter', 'year', 'month'), name='consumption__constraint'),
        ),
    ]
