# Generated by Django 3.2.5 on 2021-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_fix_constraint_add_reading_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumption',
            name='consumption__constraint',
        ),
        migrations.AddConstraint(
            model_name='consumption',
            constraint=models.UniqueConstraint(fields=('facility', 'account', 'meter', 'year', 'month', 'reading_type', 'allocated_consumption'), name='consumption__constraint'),
        ),
    ]
