# Generated by Django 3.2.5 on 2021-07-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_add_charlength'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumption',
            name='consumption__constraint',
        ),
    ]
