# Generated by Django 3.2.5 on 2021-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epa_energy_type', models.CharField(max_length=50, unique=True)),
                ('site_to_source_ratio', models.FloatField()),
                ('kbtu_coeff', models.FloatField()),
                ('co2e_coeff', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='coefficientrecord',
            index=models.Index(fields=['epa_energy_type'], name='facilities__epa_ene_b7254b_idx'),
        ),
    ]
